import csv
f=open("All.csv","w+",newline="")
wtrobj=csv.writer(f)
wtrobj.writerows([["Birds of prey","https://youtu.be/kGM4uYZzfu0"],
                  ["The Invisible Man","https://www.youtube.com/watch?v=WO_FJdiY9dA"],
                  ["Black Panther","https://www.youtube.com/watch?v=xjDjIWPwcPU"],
                  ["Mission:Impossible-Fallout","https://www.youtube.com/watch?v=wb49-oV0F78"],
                  ["Mulan","https://www.youtube.com/watch?v=KK8FHdFluOQ"],
                  ["UP","https://www.youtube.com/watch?v=pkqzFUhGPJg"],
                  ["Freaky Friday","https://www.youtube.com/watch?v=nZ8KJ4MzzOw"],
                  ["Apollo 13","https://www.youtube.com/watch?v=KtEIMC58sZo"],
                  ["Coco","https://www.youtube.com/watch?v=Rvr68u6k5sI"],
                  ["The Underwater","https://www.youtube.com/watch?v=jCFWEzIVILc"],
                  ["Black Widow","https://www.youtube.com/watch?v=ybji16u608U"],
                  ["2001: A Space Odyssey (1968)","https://youtu.be/Z2UWOeBcsJI"],
                  ["The Dark Knight","https://www.youtube.com/watch?v=EXeTwQWrcwY"],
                  ["Once Upon a Time in Hollywood","https://www.youtube.com/watch?v=ELeMaP8EPAA"],
                  ["Call Me By Your Name ","https://youtu.be/Z9AYPxH5NTM"],
                  ["The Hurt Locker","https://www.youtube.com/watch?v=AIbFvqFYRT4"],
                  ["Eden","https://www.youtube.com/watch?v=EXxQ52VaJPQ"],
                  ["Stories We Tell","https://www.youtube.com/watch?v=A_8BnZ471GY"],
                  ["Capernaum","https://www.youtube.com/watch?v=ULUo0048xZE"],
                  ["Love & Friendship","https://youtu.be/8MaSK3POHI0"],
                  ["The Conjuring 2","https://www.youtube.com/watch?v=VFsmuRPClr4"],
                  ["Joker","https://www.youtube.com/watch?v=-_DJEzZk2pc"],
                  ["Ghostbusters","https://www.youtube.com/watch?v=w3ugHP-yZXw"],
                  ["Annabelle Comes Home","https://www.youtube.com/watch?v=bCxm7cTpBAs"],
                  ["The Shallows","https://www.youtube.com/watch?v=EgdxIlSuB70"],
                  ["Bruce Almighty","https://www.youtube.com/watch?v=0XBxoKumlqQ"],
                  ["Get Out","https://www.youtube.com/watch?v=DzfpyUB60YY"],
                  ["Captain America: Civil War","https://www.youtube.com/watch?v=dKrVegVI0Us"],
                  ["Guardians Of The Galaxy","https://www.youtube.com/watch?v=d96cjJhvlMA"],
                  ["A Prophet","https://www.youtube.com/watch?v=l69ARbQt-Ko"],
                  ["Batman Begins","https://www.youtube.com/watch?v=neY2xVmOfUM"],
                  ["Avatar","https://www.youtube.com/watch?v=6ziBFh3V1aM"],
                  ["Toy Story 3","https://www.youtube.com/watch?v=JcpWXaA2qeg"],
                  ["Wall-E","https://www.youtube.com/watch?v=qGBZWbg_26A"],
                  ["Captain America: The Winter Soldier","https://www.youtube.com/watch?v=7SlILk2WMTI"],
                  ["Star Wars: The Force Awakens","https://www.youtube.com/watch?v=sGbxmsDFVnE"],
                  ["Avengers: Endgame","https://www.youtube.com/watch?v=TcMBFSGVi1c"],
                  ["Disney's Aladdin","https://www.youtube.com/watch?v=foyufD52aog"],
                  ["Wonder Woman","https://www.youtube.com/watch?v=1Q8fG0TtVAY"],
                  ["Inside Out","https://www.youtube.com/watch?v=WIDYqBMFzfg"],
                  ["Avengers: Infinity War","https://www.youtube.com/watch?v=6ZfuNTqbHE8"],
                  ["Incredibles 2","https://www.youtube.com/watch?v=i5qOzqD9Rms"],
                  ["Moana","https://www.youtube.com/watch?v=yfCOEGyHMwc"],
                  ["Finding Dory","https://www.youtube.com/watch?v=0tkLUap7oGQ"],
                  ["Ratatouille","https://www.youtube.com/watch?v=uVeNEbh3A4U"],
                  ["The Chronicles of Narnia: The Voyage of the Dawn Treader","https://www.youtube.com/watch?v=hrJQDPpIK6I"],
                  ["Margaret","https://www.youtube.com/watch?v=7YAiS-3EhMI"],
                  ["Lights Out","https://www.youtube.com/watch?v=6LiKKFZyhRU"],
                  ["Logan","https://www.youtube.com/watch?v=Div0iP65aZo"],
                  ["Assassin's Creed (film)","https://www.youtube.com/watch?v=gfJVoF5ko1Y"],
                  ["Dangal","https://www.youtube.com/watch?v=x_7YlGv9u1g"],
                  ["3 Idiots","https://www.youtube.com/watch?v=K0eDlFX9GMc"],
                  ["Angrezi Medium","https://www.youtube.com/watch?v=rzlfeocUVhI"],
                  ["Mard Ko Dard Nahi Hota","https://www.youtube.com/watch?v=jb0-Mw_V_bA"],
                  ["Aashiqui 2","https://www.youtube.com/watch?v=Fb0qB11Sb1E"],
                  ["Dil Chahata Hai","https://www.youtube.com/watch?v=m13b25V0B10"],
                      ["Zindagi Na Milegi Dobara","https://www.youtube.com/watch?v=FJrpcDgC3zU"],
                      ["Bhavesh Joshi Superhero","https://www.youtube.com/watch?v=RYsdZHc7MI8"],
                      ["Chak De! India","https://www.youtube.com/watch?v=6a0-dSMWm5g"],
                      ["Andhadhun","https://www.youtube.com/watch?v=2iVYI99VGaw"],
                      ["Queen","https://www.youtube.com/watch?v=KGC6vl3lzf0"],
                      ["Chhichhore","https://www.youtube.com/watch?v=tsxemFX0a7k"],
                      ["M.S Dhoni: The Untold Story","https://www.youtube.com/watch?v=6L6XqWoS8tw"],
                      ["Taare Zameen Par","https://www.youtube.com/watch?v=tn_2Ie_jtX8"],
                      ["Lunchbox","https://www.youtube.com/watch?v=IJIGJtb_N7E"],
                      ["Karwaan","https://www.youtube.com/watch?v=IUCeN7kelXs"],
                      ["PK","https://www.youtube.com/watch?v=SOXWc32k4zA"],
                      ["Badla","https://www.youtube.com/watch?v=xHWQiok-ei0"],
                      ["Piku","https://www.youtube.com/watch?v=oeiKUlUUNQ8"],
                      ["Airlift","https://www.youtube.com/watch?v=vb5xCMbMfZ0"],
                      ["Khuda Haafiz","https://www.youtube.com/watch?v=ByYWL1SEe-k"],
                      ["Malang","https://www.youtube.com/watch?v=sft5baUuzQs"],
                      ["The Sky Is Pink","https://www.youtube.com/watch?v=prwUFBsDRLk"],
                      ["Dishoom","https://www.youtube.com/watch?v=DU6IdS2gVog"],
                      ["Thappad","https://www.youtube.com/watch?v=jBw_Eta0HDM"],
                      ["Lootcase","https://www.youtube.com/watch?v=Q9ij1MUCXVg"],
                      ["Luka Chuppi","https://www.youtube.com/watch?v=-JLewvWBkCw"],
                      ["Super 30","https://www.youtube.com/watch?v=QpvEWVVnICE"],
                      ["Omerta","https://www.youtube.com/watch?v=ikf3UodZJHA"],
                      ["Badhai Ho","https://www.youtube.com/watch?v=unAljCZMQYw"],
                      ["Parmanu: The Story of Pokhran","https://www.youtube.com/watch?v=qN_9DnBh3hM"],
                      ["Sanju","https://www.youtube.com/watch?v=1J76wN0TPI4"],
                      ["Raazi","https://www.youtube.com/watch?v=YjMSttRJrhA"],
                      ["Ek Villian","https://www.youtube.com/watch?v=ruO0VrqOkdE"],
                      ["Padmavaat","https://www.youtube.com/watch?v=XgUBV9p9jfk&list=PL0ZrCfkcPKNz-5Fy0uIQ2qZgAM1GXjkup&index=27&t=0s"],
                      ["October","https://www.youtube.com/watch?v=VjPePUA6MO4"],
                      ["Dil Dhakane Do","https://www.youtube.com/watch?v=qfnJCv4_1Ts"],
                      ["Haider","https://www.youtube.com/watch?v=ZmN_VSo8DOo"],
                      ["2 States","https://www.youtube.com/watch?v=CGyAaR2aWcA"],
                      ["Tumbbad","https://www.youtube.com/watch?v=sN75MPxgvX8"],
                      ["Andaz Apna Apna","https://www.youtube.com/watch?v=fd_w7Qw8biU"],
                      ["Lagaan","https://www.youtube.com/watch?v=oSIGQ0YkFxs"],
                      ["Munna Bhai MBBS","https://www.youtube.com/watch?v=6lCGvu-hwX4"],
                      ["Khoobsurat","https://m.youtube.com/watch?v=pOreDBy1YfI&list=PLjKvpT-8JGXHs2bmMBZ7vIbxIWFBEKWXW&index=7&t=0s"],
                      ["Vicky Donor","https://www.youtube.com/watch?v=Jme-VkIzkoU"],
                      ["Jab We Met","https://www.youtube.com/watch?v=i7VGyugYCIk"],
                      ["Yeh Jawaani Hai Deewani","https://www.youtube.com/watch?v=Rbp2XUSeUNE"],
                      ["Wake Up Sid","https://www.youtube.com/watch?v=Ngimy3GpHS0"],
                      ["English Vinglish","https://www.youtube.com/watch?v=wmGVY4T88dc"],
                      ["Barilly Ki Barfi","https://www.dailymotion.com/video/x5u6znl"],
                      ["Tanu Weds Manu","https://www.youtube.com/watch?v=hq0RMAuQGWA"],
                      ["Shubh Mangal Savadhan","https://www.youtube.com/watch?v=r6r8UYU7Zcs"],
                      ["Dostana","https://www.youtube.com/watch?v=PYNpmI_MHXc"],
                      ["Hera Pheri","https://www.youtube.com/watch?v=BtQqo_4ypkM"],
                      ["Dilwale Dulhania Le Jayenge","https://www.youtube.com/watch?v=cmax1C1p660Z"],
                      ["Uri: The Surgical Strike","https://www.youtube.com/watch?v=VVY3do673Zc"],
                      ["The Body","https://www.youtube.com/watch?v=4f9jIdg4rTQ"],
                      ["Hamari Adhuri Kahani","https://www.youtube.com/watch?v=2fiT_TJlySk"],
                      ["Madari","https://www.youtube.com/watch?v=j4s3JmLGLCA"],
                      ["Gangs Of Wasseypur","https://www.youtube.com/watch?v=j-AkWDkXcMY"],
                      ["Talwar","https://www.youtube.com/watch?v=aQNMsw8Ljjc"],
                      ["Rockstar","https://www.youtube.com/watch?v=bD5FShPZdpw"],
                      ["Barfi","https://www.youtube.com/watch?v=nQ3FYUgSjC8"],
                      ["Kai Po Che","https://www.youtube.com/watch?v=G19faYsLtlc"],
                      ["Gully Boy","https://www.youtube.com/watch?v=JfbxcD6biOk"],
                      ["Paan Sing Tomar","https://www.youtube.com/watch?v=A0cT7ukL4GI"],
                      ["Sholay","https://www.youtube.com/watch?v=zzTUvWfvlBg"],
                      ["Tamasha","https://www.youtube.com/watch?v=o-e5eWVCzx8"],
                      ["Bajrangi Bhaijaan","https://www.youtube.com/watch?v=Oz_ZJhcOX1E"],
                      ["Masaan","https://www.youtube.com/watch?v=SKJfBo3xMW0"],
                      ["Pink","https://www.youtube.com/watch?v=AL2TShb6fFs"],
                      ["Article 15","https://www.youtube.com/watch?v=HKOJY0cU63E"],
                      ["Mughal E Azam","https://www.youtube.com/watch?v=rXz_vWzMh_U"],
                      ["Highway","https://www.youtube.com/watch?v=LSrDD52bx4A"],
                      ["Shahid","https://www.youtube.com/watch?v=2p8LyAte-M8"],
                      ["Hindi Medium","https://www.youtube.com/watch?v=GjkFr48jk68"],
                      ["Rocket Singh - Salesman of the Year ","https://www.youtube.com/watch?v=MctcqGHpfdM"],
                      ["Hum Apke Hain Kon","https://www.youtube.com/watch?v=45JY12a6zJA"],
                      ["Koi Mil Gaya","https://www.youtube.com/watch?v=IBpZH-CFgZ0"],
                      ["Kuch Kuch Hota Hai","https://www.youtube.com/watch?v=05i3eIuJLaU"],
                      ["Paa","https://www.youtube.com/watch?v=mTjEWy4InQ4"],
                      ["Slumdog Millionaire","https://www.youtube.com/watch?v=AIzbwV7on6Q"],
                      ["Om Shanti Om","https://www.youtube.com/watch?v=9oeGoQGt7Ao"],
                      ["Guru","https://www.youtube.com/watch?v=D1eE-lCKcxI"],
                      ["Azhar","https://www.youtube.com/watch?v=C1MOI8vaQos"],
                      ["Padman","https://www.youtube.com/watch?v=-K9ujx8vO_A"],
                      ["Bajirao Mastani","https://www.youtube.com/watch?v=eHOc-4D7MjY"],
                      ["Kahaani","https://www.youtube.com/watch?v=j1wEeuAosNM"],
                      ["Chennai Express","https://www.youtube.com/watch?v=hZGR5Sj1Bfo"],
                      ["Batla House","https://www.youtube.com/watch?v=dG3K6jB3iW8"],
                      ["Mission Mangal","https://www.youtube.com/watch?v=q10nfS9V090"],
                      ["Baby","https://www.youtube.com/watch?v=vKXHxluLTUo"],
                      ["Kapoor And Sons","https://www.youtube.com/watch?v=s7YYt9_KfsM"],
                      ["Kaabil","https://www.youtube.com/watch?v=nubDFeiUAsI"],
                      ["Game Over","https://www.youtube.com/watch?v=BY-R6NcnkbE"],
                      ["Ae Dil Hai Mushkil","https://www.youtube.com/watch?v=Z_PODraXg4E"],
                      ["Goliyon Ki Raasleela Ram-Leela","https://www.youtube.com/watch?v=StphRCLkx6Q"],
                      ["Hasee Toh Phasee","https://www.youtube.com/watch?v=Xv5MG0LhaP4"],
                      ["Dum Laga Ke Haisha","https://www.youtube.com/watch?v=lFZpPpSU3k0&vl=en"],
                      ["Bala","https://www.youtube.com/watch?v=veJ6ejMjzgE"],
                      ["Badlapur","https://www.youtube.com/watch?v=9KEoZanqlOE"],
                      ["Shylock","https://www.youtube.com/watch?v=yuroURGFllQ"],
                      ["Trance","https://www.youtube.com/watch?v=uSudz8zb2I8"],
                      ["Driving license","https://www.youtube.com/watch?v=8pXjSuTdV7o"],
                      ["Oppam","https://www.youtube.com/watch?v=YKXq5jTuQSc"],
                      ["Odiyan","https://www.youtube.com/watch?v=e1BHZ4Jtg-A"],
                      ["Kumbalangi nights","https://www.youtube.com/watch?v=3P4BFBSafF0"],
                      ["Forensic","https://www.youtube.com/watch?v=zTBzGaiAzwY"],
                      ["Mamangam","https://www.youtube.com/watch?v=hCU_B_QKVR4"],
                      ["Madhura raja","https://www.youtube.com/watch?v=qhOtGVRGfSg"],
                      ["Masterpiece","https://www.youtube.com/watch?v=1vOck2Nguso"],
                      ["Puthan panam","https://www.youtube.com/watch?v=IyJAhnrAmUE"],
                      ["Pokkiri raja","https://www.youtube.com/watch?v=om8Ce6oLclk"],
                      ["Lucifer","https://www.youtube.com/watch?v=x1-Ya0NZQso"],
                      ["Love action drama","https://www.youtube.com/watch?v=nmd2M-3k-Ds"],
                      ["Christian brothers","https://www.youtube.com/watch?v=m0PmnALzVD4"],
                      ["Premam","https://www.youtube.com/watch?v=pbgvTikmIMk"],
                      ["Kayamkulam kochunni","https://www.youtube.com/watch?v=0XO03BdZi2Y"],
                      ["Pathinettan padi","https://www.youtube.com/watch?v=22rLzgXTC8g"],
                      ["Abrahaminte santhathikal","https://www.youtube.com/watch?v=1jhbgD4BGvM"],
                      ["Ramaleela","https://www.youtube.com/watch?v=j3UN0nF_KbE"],
                      ["Bangalore days","https://www.youtube.com/watch?v=uVpHL5g4buY"],
                      ["Jomonte suvisheshangal","https://www.youtube.com/watch?v=dmYUI536bZI&list=PL07fTLkdmLo7W94SiqFgxxHcTSRJAS2bR&index=2&t=0s"],
                      ["Maheshinte prathikaram","https://www.youtube.com/watch?v=Fdz7NUf9G5w&list=PLIU90_mrhapP1acGNZpoHehUEyVTPUntl&index=63"],
                      ["Iyobinte Pusthakam","https://www.youtube.com/watch?v=IbD5Baz0kOI"],
                      ["CIA","https://www.youtube.com/watch?v=f5nvCp0QFdA"],
                      ["Kammara Sambhavam","https://www.youtube.com/watch?v=UKkNcfTvVjI"],
                      ["Drishyam","https://www.youtube.com/watch?v=AuuX2j14NBg"],
                      ["Munthirivallikal Thalirkkumbol","https://m.youtube.com/watch?v=8qHITluVfX8&list=PLkXZ7hMQPTvCdKwgOWHjel2Minn8DFVKu&index=5&t=0s"],
                      ["Puthiya Niyamam","https://www.youtube.com/watch?v=dX8snwD0MEA"],
                      ["Charlie","https://www.youtube.com/watch?v=oYxtLNJJ54Y"],
                      ["Puthiya Mugham","https://www.youtube.com/watch?v=TwgNaNXsOMY"],
                      ["Action hero biju","https://www.youtube.com/watch?v=bJgV9eC0GJE"],
                      ["Ohm shanthi Oshaana","https://www.youtube.com/watch?v=M5-mzpNvnrY"],
                      ["Varathan","https://www.youtube.com/watch?v=STHwR_ZzEGU"],
                      ["Amar Akbar Anthony","https://www.youtube.com/watch?v=s3Q6AM4MDs4"],
                      ["Pretham","https://www.youtube.com/watch?v=EjIYhkH3ztw&list=PLw94rwVRhBKV0IbcFfS7BynYsp-x30VuC&index=21"],
                      ["Vikramadithyan","https://www.youtube.com/watch?v=mUCWhRnBb7s"],
                      ["Take off","https://www.youtube.com/watch?v=vzYSKjxtKNg"],
                      ["Solo","https://www.youtube.com/watch?v=BXCUqa9cboI&list=PLaENq2b0ZqjWb0oJj1VBXnfRHYu9L2Or9&index=10&t=0s"],
                      ["Moothon","https://www.youtube.com/watch?v=XqHGkcvDAEE&list=PLhiVAW-D5_GC8DJX9X7l-6FTndxV2TBwV&index=46"],
                      ["Sakhavu","https://www.youtube.com/watch?v=VRqEXJ-bpZI&list=PLTihxqJD1mfAc4y9nCWLgWskn0UGmzsPh"],
                      ["Mr. Fraud","https://www.youtube.com/watch?v=URZkb9AxkQI"],
                      ["Anjaam Pathiraa","https://www.youtube.com/watch?v=dn5KZD1E67Y"],
                      ["Virus","https://www.youtube.com/watch?v=38MijVTyP7s"],
                      ["Kettyolaanu Ente Malakha","https://www.youtube.com/watch?v=wxyi6zkC1G4"],
                      ["Helen","https://www.youtube.com/watch?v=Z12zJCpj95w"],
                      ["Pretham 2","https://www.youtube.com/watch?v=j3uaKtT7PtE"],
                      ["Jamna Pyari","https://www.youtube.com/watch?v=ScyhCXI9VzE"],
                      ["Big Brother","https://www.youtube.com/watch?v=GAY3jdx1PoA"],
                      ["Thoppil Joppan","https://www.youtube.com/watch?v=B7RBtZGbj2Q"],
                      ["Unda","https://www.youtube.com/watch?v=KxeMmKULuZk"],
                      ["Velipadinte Pusthakam","https://www.youtube.com/watch?v=wch_ORhMU5g"],
                      ["Pulimurugan","https://www.youtube.com/watch?v=blQUlD8g4Pk"],
                      ["Pullikkaran Staraa","https://www.youtube.com/watch?v=hez3gYfnra4"],
                      ["Pathemari","https://www.youtube.com/watch?v=a95a2qy_fl4"],
                      ["Thrissur pooram","https://www.youtube.com/watch?v=X-lcmMNli_w"],
                      ["Jacobinte Swargarajyam","https://www.youtube.com/watch?v=ydHzDHz12fw"],
                      ["Rajamanikam","https://www.youtube.com/watch?v=hez3gYfnra4"],
                      ["Varane Avashyamund","https://www.youtube.com/watch?v=M3i-VGCY69c"],
                      ["Sudani from Nigeria","https://www.youtube.com/watch?v=EHyaTJGmN4k"],
                      ["Angamaly Diaries","https://www.youtube.com/watch?v=4yRBJCrjabU"],
                      ["Thondimuthalum Driksakshiyum","https://www.youtube.com/watch?v=f2zG7g4AVoQ"],
                      ["Njan Prakashan","https://www.youtube.com/watch?v=8EVi5VByNNg"],
                      ["Ustad hotel","https://www.youtube.com/watch?v=rhfVeDnd7-M"],
                      ["Oru vadakkan selfie ","https://www.youtube.com/watch?v=7s0uX2u6b5w"],
                      ["Aadu","https://www.youtube.com/watch?v=4fiZ52yj4b4"],
                      ["Aadu 2","https://www.youtube.com/watch?v=_jlVhEs75Fo"],
                      ["Kuttanadan Marpappa","https://www.youtube.com/watch?v=0rUe8b6EL90"],
                      ["Parole","https://www.youtube.com/watch?v=jnhHC8xKznE"],
                      ["Aravindante Athidhikal","https://www.youtube.com/watch?v=5YIThlVcjbU"],
                      ["Kunjiramayanam","https://www.youtube.com/watch?v=iSxYYphno1s"],
                      ["The Great Father","https://www.youtube.com/watch?v=eqE4L87RI7E"],
                      ["Honey Bee 2","https://www.youtube.com/watch?v=ynKvrmsBQmY"],
                      ["Honey Bee 2.5","https://www.youtube.com/watch?v=elYLAAlr320"],
                      ["Darvinte Parinamam","https://www.youtube.com/watch?v=jGuBc-AvNxk"],
                      ["Aamis","https://www.youtube.com/watch?v=-zv11DpavFI"],
                      ["Kothanodi","https://www.youtube.com/watch?v=rgzYIOV374I"],
                      ["Village rockstars","https://www.youtube.com/watch?v=tTov2nVgXaU"],
                      ["Hellaro","https://www.youtube.com/watch?v=qb8uOylK3R4"],
                      ["Goodachari","https://www.youtube.com/watch?v=V-8GGhn0oDk"],
                      ["Kavaludaari","https://www.youtube.com/watch?v=5w1vgMoPMRA"],
                      ["Agent Sai Srinivasa Athreya","https://www.youtube.com/watch?v=iPfVbR5oAWE"],
                      ["HIT:The first case","https://www.youtube.com/watch?v=uYdsWe9iBAA"],
                      ["NANI's GANGLEADER","https://www.youtube.com/watch?v=AjAe_Q1WZ_8"],
                      ["Jersey","https://www.youtube.com/watch?v=AjAe_Q1WZ_8"],
                      ["1Awe!","https://www.youtube.com/watch?v=xOEscQChX7M"],
                      ["Gentleman","https://www.youtube.com/watch?v=MgmowJ5r-es"],
                      ["Sairat","https://www.youtube.com/watch?v=wMrMKnoYWwA"],
                      ["Mathu vadalara","https://www.youtube.com/watch?v=tmb2G-C6byM"],
                      ["Gantumoote","https://www.youtube.com/watch?v=CY5c2VNaI2s"],
                      ["Rangitaranga","https://www.youtube.com/watch?v=L8wWqg2oYiQ"],
                      ["KGF:Chapter1","https://www.youtube.com/watch?v=qXgF-iJ_ezE"],
                      ["Pelli choopulu","https://www.youtube.com/watch?v=zHO7BuWCHK8"],
                      ["Lucia","https://www.youtube.com/watch?v=pgIL2H-OdcA"],
                      ["Kirik Party","https://www.youtube.com/watch?v=IfvnbER_6sQ"],
                      ["Ulidavaru Kandante","https://www.youtube.com/watch?v=POJ_6EtGeMw"],
                      ["Avane Srimannarayana","https://www.youtube.com/watch?v=Dj-HNEZ59Z4"],
                      ["The gangster,the cop,the devil","https://www.youtube.com/watch?v=hS-fztIL8HE"],
                      ["Oldboy","https://www.youtube.com/watch?v=2HkjrJ6IK5E"],
                      ["Parasite","https://www.youtube.com/watch?v=5xH0HfJHsaY"],
                      ["I saw the devil","https://www.youtube.com/watch?v=xwWgp1bqVwE"],
                      ["Train to Busan","https://www.youtube.com/watch?v=pyWuHv2-Abk"],
                      ["Peninsula","https://www.youtube.com/watch?v=2kE1Ydf4jIo"],
                      ["U-Turn","https://www.youtube.com/watch?v=Kdh5P8dtMXA"],
                      ["Yatra","https://www.youtube.com/watch?v=OuIJDxLeEBc"],
                      ["Godhi banna sadharana mykattu","https://www.youtube.com/watch?v=aPk9fBdtugg"],
                      ["Uma maheswara ugra roopasya","https://www.youtube.com/watch?v=ggzOfWWpoK8"],
                      ["C/o Kancharapalem","https://www.youtube.com/watch?v=-YeQZwlNeaY"],
                      ["Rangasthalam","https://www.youtube.com/watch?v=sueMmTm-M4Y"],
                      ["Oopiri","https://www.youtube.com/watch?v=e1ddsJ38D5Q"],
                      ["Thithi","https://www.youtube.com/watch?v=Q_NltD4Stv4"],
                      ["Dia","https://www.youtube.com/watch?v=mMqcXDkCRLs"],
                      ["Mufti","https://www.youtube.com/watch?v=PdH5AcS7BR4"],
                      ["Ugramm","https://www.youtube.com/watch?v=f7XQSsZLjmo"],
                      ["Katha Sangama","https://www.youtube.com/watch?v=2a8hE5Y9pH4"],
                      ["Memories of murder","https://www.youtube.com/watch?v=-YvWR3Bds0A"],
                      ["Miracle in cell no.7","https://www.youtube.com/watch?v=tvJQoFGKA0Y"],
                      ["Natarang","https://www.youtube.com/watch?v=CnXdnNAyaY0"],
                      ["Natsamrat","https://www.youtube.com/watch?v=DCXDyIsPEN8"],
                      ["Bulbul can sing","https://www.youtube.com/watch?v=6DsjnhSR9ww"],
                      ["Evaru","https://www.youtube.com/watch?v=TfW6lil5uyc"],
                      ["Kshanam","https://www.youtube.com/watch?v=OroFSmQQm1U"],
                      ["Ratsasan","https://www.youtube.com/watch?v=GsrN7rNch9Y"],
                      ["Peranbu","https://www.youtube.com/watch?v=1Nk7bEYIA7c"],
                      ["24","https://www.youtube.com/watch?v=wqXE_es_I3M"],
                      ["Sarkar","https://www.youtube.com/watch?v=VkkyaodksT4"],
                      ["Labaam","https://www.youtube.com/watch?v=e0gX_cFKEng"],
                      ["Vikramvedha","https://www.youtube.com/watch?v=1sVr-uWZPjE"],
                      ["I","https://www.youtube.com/watch?v=8uPK9Ov6Zd4"],
                      ["96","https://www.youtube.com/watch?v=r0synl-lI4I"],
                      ["Enthiran","https://www.youtube.com/watch?v=ODxHJasuCx4"],
                      ["Indian","https://www.youtube.com/watch?v=BbzKMT0MM7k"],
                      ["Nayakan","https://www.youtube.com/watch?v=XX25ea8PeFk"],
                      ["Super deluxe","https://www.youtube.com/watch?v=3-Xq_Zz3nPA"],
                      ["Ok kanmani","https://www.youtube.com/watch?v=2mBG4vlhcCc"],
                      ["Raavan","https://www.youtube.com/watch?v=7ZpY7_mpD4k"],
                      ["Bombay","https://www.youtube.com/watch?v=vIZmPQaDuI8"],
                      ["Thalapathy","https://www.youtube.com/watch?v=pC5yWXqb8Ys"],
                      ["Pithamagan","https://www.youtube.com/watch?v=rycv49ClLao"],
                      ["Anniyan","https://www.youtube.com/watch?v=bzAxJDtS7zE"],
                      ["Asuran","https://www.youtube.com/watch?v=vOCM9wztBYQ"],
                      ["Kaithi","https://www.youtube.com/watch?v=pC5yWXqb8Ys"],
                      ["Kannum kannum kolllaiyadithaal","https://www.youtube.com/watch?v=hPybzXeEWSI"],
                      ["Chekka chivantha vaanam","https://www.youtube.com/watch?v=x2q5w-ThJeE"],
                      ["Vaaranam aayiram","https://www.youtube.com/watch?v=QdM9L1FxFkY"],
                      ["Ghajini","https://www.youtube.com/watch?v=_I0xx8Oj3Ww"],
                      ["Naachiyaar","https://www.youtube.com/watch?v=DTtnh86GnTY"],
                      ["Anjaan","https://www.youtube.com/watch?v=MJxEQPMh_io"],
                      ["Kaththi","https://www.youtube.com/watch?v=bMf0IyzyKt4"],
                      ["Sethupathi","https://www.youtube.com/watch?v=dK5E8mzmD6w"],
                      ["Mankatha","https://www.youtube.com/watch?v=vHESM8iR1JE"],
                      ["Billa","https://www.youtube.com/watch?v=E2e6-Vi-VKs"],
                      ["Thambi","https://www.youtube.com/watch?v=y2vwIiLyt1Y"],
                      ["Madrasapattinam","https://www.youtube.com/watch?v=NrPKdhtovGw"],
                      ["Aarambam","https://www.youtube.com/watch?v=FltdImg7FPE"],
                      ["Vettaiyaadu Vilaiyaadu","https://www.youtube.com/watch?v=KSDAAqf6Img"],
                      ["Avvai Shanmughi","https://www.youtube.com/watch?v=D3ESUmGa9qY"],
                      ["Uttama Villain","https://www.youtube.com/watch?v=fD4F_dQgDUs"],
                      ["Aaranya Kaandam","https://www.youtube.com/watch?v=qBJ_UpyQw_s"],
                      ["Roja","https://www.youtube.com/watch?v=0GquoOZfkOc"],
                      ["Baasha","https://www.youtube.com/watch?v=1g-yZ3BDDK0"],
                      ["Oh Baby","https://www.youtube.com/watch?v=rinPndsJVrc"],
                      ["Oh my Kadavule","https://www.youtube.com/watch?v=5lUWBM2uYaQ"],
                      ["Anbe Sivam","https://www.youtube.com/watch?v=lPLN69KAukE"],
                      ["Mounaraagam","https://www.youtube.com/watch?v=zKN7LOs5Z5o"],
                      ["Alaipayuthe","https://www.youtube.com/watch?v=ez_XsttP9Es"],
                      ["papanaasam","https://www.youtube.com/watch?v=qTnYaTYl9RQ"],
                      ["Pariyerum perumal","https://www.youtube.com/watch?v=GMNsUxJe4R4"],
                      ["Visaaranai","https://www.youtube.com/watch?v=4mnzK2KIz9U"],
                      ["Joker","https://www.youtube.com/watch?v=4xr59w5r6Hw"],
                      ["Maanaragam","https://www.youtube.com/watch?v=R7MR12XOMGQ"],
                      ["Dhruvangal pathinaaru","https://www.youtube.com/watch?v=xpt2jfiL5GY"]])
f.close()     


def Display():
    f=open("All.csv","r")
    mov_reader=csv.reader(f)
    Var=0
    next(mov_reader)
    try:
        for rec in mov_reader:
            print(rec[0])
            Var+=1
        print("Total Number of Movies In the database:",Var,"movies")
    except IndexError:
        pass
    f.close()

def Search():
    f=open("All.csv","r")
    mov_reader=csv.reader(f)
    Movie_Name=input("Enter the Movie Name that you want to Search:")
    Var=False
    for rec in mov_reader:
        if rec[0].casefold()==Movie_Name.casefold():
            Var=True
    if Var==True:
        print("Movie Found")
    else:
        print("Movie Not Found!")
    

while True:
    var=input("1.Press D to display the movies in the database.\n2.Press S to search if a movie is in the database.\n3.Press E to Exit.\n")
    #if var in "Aa":
        #Add()
    if var in "Dd":
        Display()
    elif var in "Ss":
        Search()
    elif var in "Ee":
        break
    else:
        continue
    



